#                                         #
#              rSela - v1.0.0             #
#              Author: Rishon             #
# GitHub: https://github.com/Rishon/rSela #
version: 1.0.0 # Do not touch!
check-for-updates: true


Alert: # Manage the /alert command
  command: "alert"
  usage: "&7Usage: /alert"
  permission:
  chat-message: true
  title-message: true
  actionbar-message: true
  message: "&e[ALERT] &f%executor%&8: &c%message%"
  title: "&eALERT"
  subtitle: "&c%message%" # Leave empty for no subtitle.
  actionbar: "&e[ALERT] &f%executor%&8: &c%message%"