#                                           #
#              rSela - v1.0.1               #
#              Author: Rishon               #
#  GitHub: https://github.com/Rishon/rSela  #

version: 1.0.1 # Do not touch!

# Server MOTD
# gradient colors are supported. ex. <yellow> Hello!
# You can use "\n" to break line.
MOTD:
  description: "<gradient:aqua:blue>Amazing Server</gradient>"

# Network Maintenance
# false = Allowing player connections.
# true = Blocking player connecting to the server.
# You can use "\n" to break line.
Maintenance:
  status: false
  bypass-permission: "rsela.maintenance.bypass"
  kick-message: "&cNetwork Maintenance\n\n&aTry again later."

# Commands #
Commands:
  Message: # Manage the /message command
    enabled: true
    command: "message"
    usage: "&7Usage: /message <player> <message>"
    require-permission: false
    permission: "rsela.command.message"
    message: "&e[ALERT] &f%executor%&8: &c%message%"
    player-offline: "&c%target% &7is offline."
    message-format: "&e%sender% &6-> &e%target%&8: &f%message%"
    aliases:
      - msg
  Maintenance: # Manage the /maintenance command
    enabled: true
    command: "maintenance"
    usage: "&7Usage: /maintenance <on/off> &8| &7Status: &e%status%"
    require-permission: true
    permission: "rsela.command.maintenance"
    on-message: "&cMaintenance-mode &7has been &aenabled!"
    off-message: "&cMaintenance-mode &7has been &cdisabled!"
    already-on-message: "&cMaintenance-mode &7is already enabled."
    already-off-message: "&cMaintenance-mode &7is already disabled."
    aliases: []
  Alert: # Manage the /alert command
    enabled: true
    command: "alert"
    usage: "&7Usage: /alert <message>"
    require-permission: true
    permission: "rsela.command.alert"
    chat-message: true
    title-message: true
    actionbar-message: true
    message: "&e[ALERT] &f%executor%&8: &c%message%"
    title: "&eALERT" # Leave empty for no subtitle.
    subtitle: "&c%message%" # Leave empty for no subtitle.
    actionbar: "&e[ALERT] &f%executor%&8: &c%message%"
    aliases: []
  Find: # Manage the /find command
    enabled: true
    command: "find"
    usage: "&7Usage: /find <player>"
    require-permission: true
    permission: "rsela.command.find"
    offline-message: "&c%target% &7is offline."
    online-message: "&c%target% &7is online! &8| &7Server: &e%server%"
    aliases: []
  Send: # Manage the /send command
    enabled: true
    command: "send"
    usage: "&7Usage: /send <player/all> <server>"
    require-permission: true
    permission: "rsela.command.send"
    player-offline: "&c%target% &7is offline."
    invalid-server: "&cInvalid Server: &e%server%"
    already-in-server: "&c%target% &7is already connected to %server%"
    sent-player: "&7You have sent &c%target% &7to &e%server%"
    sent-all: "&7Sending &call of the players &7to &e%server%"
    aliases: []
  ServerSend: # Manage the /serversend command
    enabled: true
    command: "serversend"
    usage: "&7Usage: /serversend <server> <server>"
    require-permission: true
    permission: "rsela.command.serversend"
    invalid-server: "&cInvalid Server: &e%server%"
    same-target: "&cFirst server and Secondary server cannot be the same."
    sent-players: "&7Sending &e%firstServer% &7players to &e%secondaryServer% &7server."
    aliases: []
  IP: # Manage the /ip command
    enabled: true
    command: "ip"
    usage: "&7Usage: /ip <player>"
    require-permission: true
    permission: "rsela.command.ip"
    offline-message: "&c%target% &7is offline."
    online-message: "&c%target% &7IP-Address is &e%ip%"
    aliases: []
  StaffChat: # Manage the /staffchat command
    enabled: true
    command: "staffchat"
    usage: "&7Usage: /staffchat <message>"
    require-permission: true
    permission: "rsela.command.staffchat"
    staff-format: "&c[STAFF-CHAT] &7| &e%executor% &7(%server%)&8: &a%message%"
    aliases:
      - sc